ecr:
  aws_profile: default
  region: us-east-1
  ecrurl: 727357989976.dkr.ecr.us-east-1.amazonaws.com

  repos:
    - scanningimages
    - replicascanningimages

  image_versions:
    - latest
    - minikube
    - 2.0
    - mysql